name: AntMaze-abstargetobs-mul
env:
  name: AntMaze
  steps: 500  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 3000
  lr: 0.01
  sigma: 0.02
hrl:
  interval: 25
  cdist: 4
  onehot: false
  prim_specific_obs: false