name: AntGather-pre
env:
  name: AntGather
  steps: 500  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 1000  # policies in one generation
  generations: 3000
hrl:
  pretrained_ctrl: ""
  pretrained_prim: "../ScalableES/saved/flagrun-pretrained/policy-obstat-opt-gen950.bson"
  interval: 25
  cdist: 4
  onehot: false
  prim_specific_obs: true