gather_tune-100int:
  overrides:
    hrl:
      interval: 100
  name: "tune_interval-100"
  nruns: 3
  path: "config/base/gather.yml"
maze_tune-100int:
  overrides:
    hrl:
      interval: 100
  name: "tune_interval-100"
  nruns: 3
  path: "config/base/maze.yml"
push_tune-100int:
  overrides:
    hrl:
      interval: 100
  name: "tune_interval-100"
  nruns: 3
  path: "config/base/push.yml"
gather_tune-10int:
  overrides:
    hrl:
      interval: 10
  name: "tune_interval-10"
  nruns: 3
  path: "config/base/gather.yml"
maze_tune-10int:
  overrides:
    hrl:
      interval: 10
  name: "tune_interval-10"
  nruns: 3
  path: "config/base/maze.yml"
push_tune-10int:
  overrides:
    hrl:
      interval: 10
  name: "tune_interval-10"
  nruns: 3
  path: "config/base/push.yml"