gather-tuned:
  name: "tuned"
  nruns: 5
  path: "config/tuned/gather.yml"
maze-tuned:
  name: "tuned"
  nruns: 5
  path: "config/tuned/maze.yml"
push-tuned:
  name: "tuned"
  nruns: 5
  path: "config/tuned/push.yml"
