maze_tune-cdist-4:
  overrides:
    hrl:
      cdist: 4
  name: "tune_cdist-4"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-ppg-1000:
  overrides:
    training:
      policies: 1000
  name: "tune_ppg-1000"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-interval-100:
  overrides:
    hrl:
      interval: 100
  name: "tune_interval-100"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-eps-3:
  overrides:
    training:
      episodes: 3
  name: "tune_eps-3"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-sigma-0.2:
  overrides:
    training:
      sigma: 0.2
  name: "tune_sigma-0.2"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-ppg-240:
  overrides:
    training:
      policies: 240
  name: "tune_ppg-240"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-lr-0.1:
  overrides:
    training:
      lr: 0.1
  name: "tune_lr-0.1"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-lr-0.01:
  overrides:
    training:
      lr: 0.01
  name: "tune_lr-0.01"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-sigma-0.02:
  overrides:
    training:
      sigma: 0.02
  name: "tune_sigma-0.02"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-interval-25:
  overrides:
    hrl:
      interval: 25
  name: "tune_interval-25"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-cdist-2:
  overrides:
    hrl:
      cdist: 2
  name: "tune_cdist-2"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-lr-0.001:
  overrides:
    training:
      lr: 0.001
  name: "tune_lr-0.001"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-interval-10:
  overrides:
    hrl:
      interval: 10
  name: "tune_interval-10"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-eps-5:
  overrides:
    training:
      episodes: 5
  name: "tune_eps-5"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-sigma-0.002:
  overrides:
    training:
      sigma: 0.002
  name: "tune_sigma-0.002"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-ppg-500:
  overrides:
    training:
      policies: 500
  name: "tune_ppg-500"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-cdist-8:
  overrides:
    hrl:
      cdist: 8
  name: "tune_cdist-8"
  nruns: 3
  path: "config/base/maze.yml"
maze_tune-eps-10:
  overrides:
    training:
      episodes: 10
  name: "tune_eps-10"
  nruns: 3
  path: "config/base/maze.yml"
