name: flagrun-i100-d4
env:
  steps: 1000  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 500
hrl:
  pretrained: ""
  interval: 100
  cdist: 4