name: antmaze-donefix-nohot
env:
  name: AntMaze
  steps: 1000  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 700
hrl:
  pretrained: ""
  interval: 50
  cdist: 4
  onehot: false