name: testgather
env:
  name: AntGather
  steps: 1000  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 700
hrl:
  pretrained_ctrl: ""
  # pretrained_prim: ""
  pretrained_prim: "/home/sasha/Documents/es/ScalableES/saved/remote/flagrun-i25-pretrain-fix-x30/policy-obstat-opt-gen600.bson"
  interval: 25
  cdist: 4
  onehot: false
  prim_specific_obs: true