name: AntGather-pretrained
env:
  name: AntGather
  steps: 500  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 700
hrl:
  pretrained_ctrl: ""
  pretrained_prim: ""
  interval: 25
  cdist: 4
  onehot: false
  prim_specific_obs: false