name: AntMaze-ns-pos_test
env:
  name: AntMaze
  steps: 500  # max steps for env
training:
  episodes: 5  # episodes per policy
  policies: 256  # policies in one generation
  generations: 700

  pop_size: 3  # number of distinct 'main' policies (for novelty search)
  behv_freq: -1
  min_nov_w: 0.5
hrl:
  pretrained_ctrl: ""
  pretrained_prim: ""
  interval: 25
  cdist: 4
  onehot: false
  prim_specific_obs: true